# Panka Infrastructure Configuration
# This is an example configuration showing various resource types

---
# Stack definition
apiVersion: panka.dev/v1
kind: Stack
metadata:
  name: my-stack
  labels:
    environment: development
spec:
  description: Example infrastructure stack
  region: us-east-1

---
# S3 Bucket for uploads
apiVersion: panka.dev/v1
kind: S3
metadata:
  name: uploads
  stack: my-stack
  service: backend
spec:
  bucket:
    acl: private
  versioning:
    enabled: true
  encryption:
    enabled: true
    algorithm: AES256

---
# DynamoDB Table for sessions
apiVersion: panka.dev/v1
kind: DynamoDB
metadata:
  name: sessions
  stack: my-stack
  service: backend
spec:
  billing_mode: PAY_PER_REQUEST
  hash_key:
    name: userId
    type: S
  range_key:
    name: sessionId
    type: S
  ttl:
    enabled: true
    attribute_name: expiresAt

---
# SQS Queue for processing
apiVersion: panka.dev/v1
kind: SQS
metadata:
  name: processing
  stack: my-stack
  service: backend
spec:
  type: standard
  visibility_timeout: 300
  message_retention_period: 345600
  receive_wait_time: 20

---
# SNS Topic for notifications
apiVersion: panka.dev/v1
kind: SNS
metadata:
  name: notifications
  stack: my-stack
  service: backend
spec:
  display_name: Notifications Topic
  subscriptions:
    - protocol: email
      endpoint: admin@example.com
